---
title: "git_00"
author: "Kyarachelle King"
date: "Year 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->  


The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->



The city had withdrawn into itself  
And left at last the country to the country;  
When between whirls of snow not come to lie  
And whirls of foliage not yet laid, there drove  
A stranger to our yard, who looked the city,  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->


"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->


The kings they came from out the south,  
   All dressed in ermine fine;  
They bore Him gold and chrysoprase,  
   And gifts of precious wine.  
 
The shepherds came from out the north,  
   Their coats were brown and old;  
They brought Him little new-born lambs—  
   They had not any gold.  
 
The wise men came from out the east,  
   And they were wrapped in white;  
The star that led them all the way  
   Did glorify the night.  
 
The angels came from heaven high,  
   And they were clad with wings;  
And lo, they brought a joyful song  
   The host of heaven sings.  
 
The kings they knocked upon the door,  
   The wise men entered in,  
The shepherds followed after them  
   To hear the song begin.  
